// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8GkXjaYJTetTDxj5_CiSZgAj4Itnls4g',
    appId: '1:499498487015:web:609eff96487600c9ad6642',
    messagingSenderId: '499498487015',
    projectId: 'svqualification',
    authDomain: 'svqualification.firebaseapp.com',
    storageBucket: 'svqualification.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbazP6HI4QVc1xU3-IjhvYbG-VjCaW6F0',
    appId: '1:499498487015:android:81e04247b3052284ad6642',
    messagingSenderId: '499498487015',
    projectId: 'svqualification',
    storageBucket: 'svqualification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNQM5w1t2MxiYW-S3FQgvfj1JT9F9MW4M',
    appId: '1:499498487015:ios:53d6bcd2991eca61ad6642',
    messagingSenderId: '499498487015',
    projectId: 'svqualification',
    storageBucket: 'svqualification.appspot.com',
    iosClientId: '499498487015-iujhi0ju9dqanfobs6k3omba8hp3iktl.apps.googleusercontent.com',
    iosBundleId: 'com.example.siliconVillage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNQM5w1t2MxiYW-S3FQgvfj1JT9F9MW4M',
    appId: '1:499498487015:ios:53d6bcd2991eca61ad6642',
    messagingSenderId: '499498487015',
    projectId: 'svqualification',
    storageBucket: 'svqualification.appspot.com',
    iosClientId: '499498487015-iujhi0ju9dqanfobs6k3omba8hp3iktl.apps.googleusercontent.com',
    iosBundleId: 'com.example.siliconVillage',
  );
}
